// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppBlock: typeof import('./src/components/AppBlock.vue')['default']
    AppButton: typeof import('./src/components/AppButton.vue')['default']
    AppImage: typeof import('./src/components/AppImage.vue')['default']
    AppInlineIcon: typeof import('./src/components/AppInlineIcon.vue')['default']
    AppSvgIcon: typeof import('./src/components/AppSvgIcon.vue')['default']
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    DialogItem: typeof import('./src/components/DialogItem.vue')['default']
    MessageAttachments: typeof import('./src/components/MessageAttachments.vue')['default']
    MessageAudio: typeof import('./src/components/MessageAudio.vue')['default']
    MessageTyping: typeof import('./src/components/MessageTyping.vue')['default']
    MessageWrapper: typeof import('./src/components/MessageWrapper.vue')['default']
    Messsage: typeof import('./src/components/Messsage.vue')['default']
    ReadedIcon: typeof import('./src/components/ReadedIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Status: typeof import('./src/components/Status.vue')['default']
    TheChatDialog: typeof import('./src/components/TheChatDialog.vue')['default']
    TheChatDialogInput: typeof import('./src/components/TheChatDialogInput.vue')['default']
    TheChatDialogMessages: typeof import('./src/components/TheChatDialogMessages.vue')['default']
    TheDialogs: typeof import('./src/components/TheDialogs.vue')['default']
    TheLoginForm: typeof import('./src/components/TheLoginForm.vue')['default']
    TheRegisterForm: typeof import('./src/components/TheRegisterForm.vue')['default']
    TheRegisterFormSuccess: typeof import('./src/components/TheRegisterFormSuccess.vue')['default']
    TheSidebar: typeof import('./src/components/TheSidebar.vue')['default']
    TheSidebarSearch: typeof import('./src/components/TheSidebarSearch.vue')['default']
    UnReadCount: typeof import('./src/components/UnReadCount.vue')['default']
  }
}

export {}
