// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AppBlock: typeof import('./src/components/AppBlock.vue')['default']
    AppButton: typeof import('./src/components/AppButton.vue')['default']
    AppImage: typeof import('./src/components/AppImage.vue')['default']
    AppSvgIcon: typeof import('./src/components/AppSvgIcon.vue')['default']
    Message: typeof import('./src/components/Message.vue')['default']
    MessageAttachments: typeof import('./src/components/MessageAttachments.vue')['default']
    MessageTyping: typeof import('./src/components/MessageTyping.vue')['default']
    MesssageText: typeof import('./src/components/MesssageText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheLoginForm: typeof import('./src/components/TheLoginForm.vue')['default']
    TheRegisterForm: typeof import('./src/components/TheRegisterForm.vue')['default']
    TheRegisterFormSuccess: typeof import('./src/components/TheRegisterFormSuccess.vue')['default']
  }
}

export {}
